#!usr/bin/python
import MySQLdb
	

db = MySQLdb.connect("localhost","root","root","library_system" )
cursor =db.cursor()
    

studentdetails_list = [ ]

class student ():

	def Student_details(self):
		try:
			print " Please enter your curiculum details below\n"
			b=raw_input("Enter your name :")
			print ("your name is " +b)
			a=raw_input("Enter your USN :")
			print ("Your USN is",int(a))
			c=raw_input("Enter your branch :")		
			print ("your  baranch is " +c)
			d=raw_input("Enter your current semester :")
			print ("you are in the semester",int(d))
			studentdetails_list.extend((a,b,c,d))
		except:
			print " Enter a valid input!!"

	def Add_student(self):
		cursor.execute("INSERT INTO student_list(First_name,Last_name,USN,Branch,Sem ) VALUES (%s,%s,%d,%s,%d)",(studentdetails_list,))
		
		cursor.commit()
		cursor.close()

	def  Display_studentlist(self):
		sql1 = """SELECT *FROM	student_list"""
		cursor.execute(sql1)
		db.commit()
	

		
bookdetails_list = [ ]
class book ():
	
	def Add_book(self):
		number= raw_input("Enter Book number\n")
		name = raw_input("Enter Book_name:\n")
		Auth_name = raw_input("Enter author_name\n")
		version = raw_input("Enter book edition\n")
		#print book_list
		sql1 ="""INSERT INTO book_list(Book_no,Book_name,Author_name,Eidition ) VALUES ('number',"name","Auth_name",'version')"""

		#sql1 ="""UPDATE book_list
		#		SET Book_no=number, Book_name="name",Author_name="Auth_name",Eidition=version"""

		cursor.execute(sql1)
		db.commit()

				
	def Display_Books(self):
		sql2 = """SELECT *FROM book_list """ 
		cursor.execute(sql2)  
		db.commit()
	
